import { AppContainer } from "@/containers/AppContainer";
import { store } from "@/redux/store";
import Head from "next/head";
import { Provider } from "react-redux";

export default function App() {
  return (
    <>
      <Head>
        <title>PsychGenApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        <AppContainer />
      </Provider>
    </>
  );
}
